# docker-compose.yml - Fixed configuration
services:
  # PostgreSQL Development Database
  postgres-dev:
    image: postgres:15-alpine
    container_name: koutu-postgres-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init-dev.sql:/docker-entrypoint-initdb.d/01-init-dev.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - koutu-test-network

  # PostgreSQL Test Database (SEPARATE from dev)
  postgres-test:
    image: postgres:15-alpine
    container_name: koutu-postgres-test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Different external port
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./docker/postgres/init-test.sql:/docker-entrypoint-initdb.d/01-init-test.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - koutu-test-network

  # Firebase Emulator Suite
  firebase-emulator:
    build:
      context: ./docker/firebase-emulator
      dockerfile: Dockerfile
    container_name: koutu-firebase-emulator
    environment:
      - NODE_ENV=test
      - FIREBASE_PROJECT_ID=demo-test-project
    ports:
      - "4000:4000"   # Firebase UI
      - "9099:9099"   # Auth Emulator
      - "9100:9100"   # Firestore Emulator
      - "9199:9199"   # Storage Emulator
    volumes:
      - firebase_emulator_data:/firebase/data
    depends_on:
      postgres-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - koutu-test-network

volumes:
  postgres_dev_data:
  postgres_test_data:
  firebase_emulator_data:

networks:
  koutu-test-network:
    driver: bridge